---
- name: Include OS-specific setup tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}/setup.yml"

- name: Include OS-specific tasks to install rustup
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}/install.yml"
